name: recsys
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - numpy
    - pandas
    - scikit-learn
    - nltk # Make sure to later install punkt after import nltk -- nltk.download('punkt')
    - jupyter
    - tqdm